title: my github journey
author: Ravi kotia
email: ravikotia278@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 hey guys here i have started my blogging journey with github and here learning is fun..

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
title: "my github journey"
date: 2021-06-29
---
